### ISSUE TITLE
Singleton services are not disposed when IIS server is stopped.

### ISSUE THREAD

**Issue by jun1sfukui** [AxaGuilDEv/extensions-dependency-injection#19]
## Summary

I made a disposable service and AddSingleton().
Then I stopped the IIS Server, but the Dispose() method hasn't been called.

## Simplest Example to Reproduce

```C#:TestService.cs
public class TestService : IDisposable {
    public TestService(){
        Debug.WriteLine("The service has been created.");
    }

    public void Dispose() {
        Debug.WriteLine("The service has been disposed.");
    }
}
```

```C#:Global.asax.cs
services.AddSingleton<TestService>();
```

```C#:HomeController.cs
pubic HomeController(TestService test) {
    
}
```

## Expected Behavior

In Debug console:
```
The service has been created.
The service has been disposed.
```

## Current Behavior

In Debug console:
```
The service has been created.
```

## Possible Solution

In Global.asax.cs add some code to dispose the provider.

```C#:Global.asax.cs
private IDisposable _provider;

public void Application_Start(){
    // creating and setting a service provider...

    _provider = provider;    
}

public void Application_End(){
    _provider?.Dispose();
}
```

## Context

Is it a correct solution?

## Your Environment

| Software         | Version |
|------------------|---------|
| `<PROJECT_NAME>` |         |
| `<BUILD_TOOL>`   |  Visual Studio 2019       |
| Operating System |   Windows 10      |

**Comment by g7ed6e** [comment]
Both MVC and WebApi packages externalize the `IServiceProvider` lifetime management to the user as the `IServiceProvider` instance is injected by constructor. I checked the [MVC/WebApi sample](https://github.com/AxaGuilDEv/extensions-dependency-injection/tree/master/samples/AxaFrance.Extensions.DependencyInjection.WebApi.Sample) and noticed that the `IServiceProvider` instance is not disposed, thus singleton are not disposed too.
You should indeed be able to get singleton instances disposed by adding the below code in Global.asax.cs file.
```
public void Application_End()
{
    ServiceProviderConfig.ServiceProvider?.Dispose();
}
```
Could you please open a pull request to fix the sample ?

**Comment by jun1sfukui** [comment]
`ServiceProviderConfig.ServiceProvider?.Dispose()` doesn't work because IServiceProvider doesn't have `Dispose()`.

~~Would it be better to change the type of `ServiceProviderConfig.ServiceProvider` to `ServiceProvider`?~~

Any solutions?

**Comment by g7ed6e** [comment]
As you suggested you could change the type of the property in the sample to be able to call Dispose method of the user provided instance of IServiceProvider.

**Comment by jun1sfukui** [comment]
I'm sorry I didn't make it clear enough.
I tried to do that, but it didn't work because the `ServiceProvider` class didn't exist in .NET Framework 4.8.
I noticed it after posting the replying message, so I added the strikethrough.

**Comment by jun1sfukui** [comment]
Actually I have tried it but it didn't work because the `ServiceProvider` class didn't exist.

I think it because of the .NET Framework version of the sample projects are 4.5.2 and the using package version of Microsoft.Extensions.DependencyInjection is very old.

I'm sorry I don't have enough time to update all projects to the latest version and try it out.

**Comment by g7ed6e** [comment]
You need to install `Microsoft.Extensions.DependencyInjection` to get acces to the `ServiceProvider` type.

**Comment by jun1sfukui** [comment]
Already installed it but the version is 1.1.1 because the packages.config of WebApi.Sample project references the very old version.
`Microsoft.Extensions.DependencyInjection` of version 1.1.1 seems to not publish the `ServiceProvider` class.

**Comment by g7ed6e** [comment]
Indeed i just checked and `ServiceProvider` is `internal` in 1.1.1.
I also checked `Microsoft.Extensions.DependencyInjection` 2.1.1 (net461, netstandard2.0), `ServiceProvider` is public in this version, thus the disposal of the ServiceProvider can be trigger by user code.

I'm closing this issue as ServiceProvider lifetime management is not handled by this package.
